---

- include: tftp.yml
  when: foreman_proxy_tftp is defined
  tags:
    - foreman-tftp
    - foreman-proxy

- name: render /etc/foreman-proxy/settings.yml
  template: src=settings.yml.j2 dest=/etc/foreman-proxy/settings.yml owner=root group={{ foreman_proxy_group }} mode=0640
  notify:
    - restart foreman-proxy
  tags:
    - foreman-proxy
    - foreman-proxy-settings
    - foreman-proxy-main-settings

- name: render foreman-proxy settings.d templates
  template: src={{ item }} dest=/etc/foreman-proxy/settings.d/{{ item | basename | regex_replace('.j2','') }} owner=root group={{ foreman_proxy_group }} mode=0640
  notify:
    - restart foreman-proxy
  with_fileglob:
    - ../templates/settings/*.j2
  when: "{{ 'foreman_proxy_' + item | basename | regex_replace('.yml.j2','') }} is defined"
  tags:
    - foreman-proxy
    - foreman-proxy-settings

- name: add foreman-proxy to named group if we are managing dns with this foreman-proxy
  user: name={{ foreman_proxy_user }} shell=/bin/false groups={{ foreman_proxy_named_group }} append=yes
  when: foreman_proxy_dns is defined
  tags:
    - foreman-proxy
    - foreman-proxy-dns

- name: enable foreman-proxy service
  service: name="foreman-proxy" state=started enabled=yes
  tags:
    - foreman-proxy
    - foreman-proxy-settings

- name: allow to connect to foreman-proxy port
  firewalld: port="{{foreman_proxy_http_port}}/tcp" permanent=true state=enabled immediate=yes
  tags:
    - foreman-proxy
