---

- include: tftp.yml
  when: foreman_proxy_tftp is defined
  tags:
    - foreman-tftp

- name: render /etc/foreman-proxy/settings.yml
  template: src=settings.yml.j2 dest=/etc/foreman-proxy/settings.yml owner=root group={{ foreman_proxy_group }} mode=0640
  notify:
    - restart foreman-proxy

- name: render foreman-proxy settings.d templates
  template: src={{ item }} dest=/etc/foreman-proxy/settings.d/{{ item | basename | regex_replace('.j2','') }} owner=root group={{ foreman_proxy_group }} mode=0640
  notify:
    - restart foreman-proxy
  with_fileglob:
    - ../templates/settings/*.j2

- name: enable foreman-proxy service
  service: name="foreman-proxy" state=started enabled=yes
